on:
  push:
    branches: [ master ]

jobs:
  tweetshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Denostuff
        id: deno
        uses: mborejdo/action-rusty@refs/heads/master
        with:
          mode: 'deno run -A --quiet ./index.ts'
          cli: ''
          infile: ''
          outfile: ''