on:
  push:
    branches: [ master ]

jobs:
  til:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generating word-cloud
        id: wcloud
        uses: mborejdo/action-rusty@refs/heads/master
        with:
          mode: 'wcloud'
          cli: '--height 480 --width 640 --min-font-size 10 --font fonts/FinkHeavy.ttf '
          infile: 'cloud.md'
          outfile: 'cloud.png'
      - name: Denostuff
        id: deno
        uses: mborejdo/action-rusty@refs/heads/master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          mode: 'deno run -A --quiet ./index.ts'
          cli: ''
          infile: ''
          outfile: ''